name: Build 6.2.2 wordpress image

# on:
#   push:
#     branches:
#       - test-CICD

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  wp-apache622:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push to Docker Repo
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./php8.0-apache-6.2.2/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/386,linux/amd64,linux/arm/v5
          push: true
          tags: ${{ secrets.DOCKERHUB_ACCOUNT }}/wordpress-apache:6.2.2
          


